# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class RedisTui < Formula
  desc "Redis TUI: view all of your redis data in the terminal"
  homepage "https://github.com/mat2cc/redis_tui"
  version "0.2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/mat2cc/redis_tui/releases/download/v0.2.0/redis_tui_Darwin_arm64.tar.gz"
      sha256 "33f4fb9c3d845cb8fa1c91ca4fff5baacee923743010655ad39fce4f84a6446c"

      def install
        bin.install "redis_tui"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/mat2cc/redis_tui/releases/download/v0.2.0/redis_tui_Darwin_x86_64.tar.gz"
      sha256 "ecd524827d9a1d77ead00c17ceec5d5834dce24852f674c38d3a65946b8ae333"

      def install
        bin.install "redis_tui"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mat2cc/redis_tui/releases/download/v0.2.0/redis_tui_Linux_arm64.tar.gz"
      sha256 "1fda980e3cfd8a66215db5db48bb6a5b9b38080b849547c58cb8c9ada387aa71"

      def install
        bin.install "redis_tui"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/mat2cc/redis_tui/releases/download/v0.2.0/redis_tui_Linux_x86_64.tar.gz"
      sha256 "d74c8810dfcee830b513bfc9206b1bcdca5fdeb32e1e3fc796b468204703b7f0"

      def install
        bin.install "redis_tui"
      end
    end
  end
end
