# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class RedisTui < Formula
  desc "Redis TUI: view all of your redis data in the terminal"
  homepage "https://github.com/mat2cc/redis_tui"
  version "0.1.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mat2cc/redis_tui/releases/download/v0.1.0/redis_tui_Darwin_x86_64.tar.gz"
      sha256 "bccbaa61edd8a0c93482449ebfc4b3faac5731a4ca54bdfad53f9d68f2d64250"

      def install
        bin.install "redis_tui"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mat2cc/redis_tui/releases/download/v0.1.0/redis_tui_Darwin_arm64.tar.gz"
      sha256 "5c928cde83af8e3edeb7a224ea81c2d48c6f93568c743beb7559fc1d0041457b"

      def install
        bin.install "redis_tui"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mat2cc/redis_tui/releases/download/v0.1.0/redis_tui_Linux_arm64.tar.gz"
      sha256 "469069b432711ad904d4196659a9001dcc1a966690aaf7afeb80d473bba6bd5b"

      def install
        bin.install "redis_tui"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/mat2cc/redis_tui/releases/download/v0.1.0/redis_tui_Linux_x86_64.tar.gz"
      sha256 "1cae548e43a994020979085a421a74056bc868672b593b420ab8975de93b616e"

      def install
        bin.install "redis_tui"
      end
    end
  end
end
